# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreFLWAutoUpdates' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreFLWAutoUpdates
  pod 'Sparkle'

  target 'CoreFLWAutoUpdatesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FLWAutoUpdates' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FLWAutoUpdates
  pod 'Sparkle'

  target 'FLWAutoUpdatesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
