name: FLWAutoUpdates
options:
  minimumXcodeGenVersion: 2.2.0
  createIntermediateGroups: true
targets:
  #macOS application
  FLWAutoUpdates:
    platform: macOS
    deploymentTarget: "10.14"
    type: application
    sources:
      - FLWAutoUpdates
    dependencies:
      - target: CoreFLWAutoUpdates
    configFiles:
      Debug: configs/FLWAutoUpdates-Debug.xcconfig
      Release: configs/FLWAutoUpdates-Release.xcconfig
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES
  # Framework Targets
  CoreFLWAutoUpdates:
    platform: macOS
    type: framework
    deploymentTarget: "10.14"
    sources:
      - CoreFLWAutoUpdates
    configFiles:
      Debug: configs/CoreFLWAutoUpdates-Debug.xcconfig
      Release: configs/CoreFLWAutoUpdates-Release.xcconfig
  #Test Targets
  FLWAutoUpdatesTests:
    platform: macOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/FLWAutoUpdatesTests.xcconfig
    sources:
      - Tests/FLWAutoUpdatesTests
    dependencies:
      - target: FLWAutoUpdates
    scheme:
      testTargets:
        - FLWAutoUpdatesTests
      gatherCoverageData: true
  CoreFLWAutoUpdatesTests:
    platform: macOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/CoreFLWAutoUpdatesTests.xcconfig
    sources:
      - Tests/CoreFLWAutoUpdatesTests
    dependencies:
      - target: CoreFLWAutoUpdates
    scheme:
      testTargets:
        - CoreFLWAutoUpdatesTests
      gatherCoverageData: true